# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            BSides Wellington  
tagline:          Bees busily breaking their way to a better world
description:      "Wellington New Zealand's Community Security Conference, NOV 23-24, 2017"
url:              "/"
baseurl:          "https://bsideswlg.github.io/"

author:
  name:           'BSides Wellington Crew'
  url:            https://twitter.com/bsideswlg

paginate:         10

github:
  repo:           https://github.com/bsideswlg/bsideswlg.github.io

  