name = "Herring Cove BSidesWlg"
description = "Herring Cove is ported from the jekyll theme of the same name. This version includes changes by the BSides Wellington team."
license = "MIT"
tags = ["blog", "company"]
min_version = 0.20

[author]
    name = "spf13, skooch"
    homepage = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "arnp"
    repo = "http://www.github.com/arnp/herring-cove"
